version : "3"


services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: chiarotti/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"
    depends_on:
      - rabbitmq

  web-mvc:
    image: chiarotti/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports: 
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - api-catalogo

  api-catalogo:
    image: chiarotti/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    ports: 
      - "5301:5301"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5301
    depends_on:
      - rabbitmq